---
db:
  clear_db_on_init: 0       # чистка БД перед тестом
  clear_db_on_destroy: 0    # чистка БД после теста
  model_type: MySQL
  name: gpbexim
  host: 127.0.0.1
  port: 3306
  user: root
  password: 'SuperStrongPass!'

  # путь от файла конфига
  schema_path: schema/MySQL.sql

xapian:
  path: temp/xapian_ui
  min: 3  # минимальное количество символов для N-грамм
  max_results: 1000
  oid_start: 0
  clear_db_on_init: 0     # чистим Xapian перед работой
  clear_db_on_destroy: 0  # чистим Xapian после работы

ui:
  max_results: 100
  server_port: 8080
  server_host: "0.0.0.0"
  template_path: 'templates/search.html'

parser:
  max_chunks:  1048576  # 1024*1024
  chunk_size: 10485760  # 1024*1024*10

log:
  use: pattern  # or 'json'
  log4perl:
    log4perl.rootLogger: INFO, Screen
    log4perl.appender.Screen: Log::Log4perl::Appender::Screen
    log4perl.appender.Screen.stderr: 1
    log4perl.appender.Screen.layout: PatternLayout
    log4perl.appender.Screen.layout.ConversionPattern: "[%d] [%p] %m%n"

  log4perl_json:
    log4perl.rootLogger: INFO, Screen
    log4perl.appender.Screen: Log::Log4perl::Appender::Screen
    log4perl.appender.Screen.stderr: 1
    log4perl.appender.Screen.layout: GPBExim::Log::JSONLayout
