---
db:
  clear_db_on_init: 1         # чистим БД перед тестом
  clear_db_on_destroy: 1      # чистим БД после теста
  model_type: SQLite3::Memory

  # путь от файла конфига
  schema_path: ../schema/SQLite3.sql
  #db_path: ../temp/sqlite3.db
  name: gpbexim

xapian:
  path: ../temp/xapian_tests  # путь от конфига
  min: 3  # минимальное количество символов для N-грамм
  max_results: 1000
  oid_start: 0
  clear_db_on_init: 0     # чистим Xapian перед работой
  clear_db_on_init: 0  # чистим Xapian после работы

ui:
  max_results: 6
  server_port: 8080
